[package]
name = "git-remote-codecommit"
description = "A git remote tool for AWS CodeCommit."
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = []
debug-probe = [] ## msrv: 1.87.0

[dependencies]
anyhow = "1.0.86"
aws-config = "1.5.3"
aws-credential-types = "1.2.0"
aws-sigv4 = { version = "1.2.2", default-features = false }
chrono = { version = "0.4.38", default-features = false, features = ["std"] }
clap = { version = "4.5.8", features = ["deprecated", "derive", "cargo", "env", "wrap_help"] }
hmac = "0.12.1"
sha2 = "0.10.8"
tokio = { version = "1.43.1", features = ["mio", "rt"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uriparse = "0.6.4"

[target."cfg(windows)".dependencies]
ctrlc = "3.4.4"
