name: Push to CodeCommit
on: # does not wait for `ci` to finish
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

concurrency:
  group: push-to-codecommit

env:
  RUST_BACKTRACE: 1
  AWS_REGION: us-west-2

jobs:
  push-to-codecommit:
    name: Push to CodeCommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need the history in order to push to CodeCommit

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::339712996426:role/github-git-remote-codecommit
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Fetch cargo dependencies
        run: cargo fetch --verbose --locked

      - name: Install git-remote-codecommit
        run: cargo install --frozen --profile=release-lto --path=crates/git-remote-codecommit

      - name: Check version
        run: git-remote-codecommit --version

      - name: Push to CodeCommit
        run: |
          git remote add aws codecommit://git-remote-codecommit
          git push aws HEAD:refs/heads/main
